"""2026-01-08

Revision ID: 108114628b3f
Revises: b1544b0c0d96
Create Date: 2026-01-08 13:48:12.689301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '108114628b3f'
down_revision: Union[str, Sequence[str], None] = 'b1544b0c0d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_daily', 'tokens_completion', schema='partner')
    op.drop_column('usage_daily', 'message_count', schema='partner')
    op.drop_column('usage_daily', 'tokens_prompt', schema='partner')
    op.drop_column('usage_daily', 'p95_latency_ms', schema='partner')
    op.drop_column('usage_daily', 'turn_count', schema='partner')
    op.drop_column('usage_daily', 'avg_latency_ms', schema='partner')
    op.add_column('usage_events', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), schema='partner')
    op.drop_index(op.f('idx_usage_events_turn_id'), table_name='usage_events', schema='partner')
    op.drop_column('usage_events', 'response_id', schema='partner')
    op.drop_column('usage_events', 'tokens_prompt', schema='partner')
    op.drop_column('usage_events', 'turn_id', schema='partner')
    op.drop_column('usage_events', 'tokens_completion', schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('tokens_completion', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_events', sa.Column('turn_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='partner')
    op.add_column('usage_events', sa.Column('tokens_prompt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_events', sa.Column('response_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='partner')
    op.create_index(op.f('idx_usage_events_turn_id'), 'usage_events', ['turn_id'], unique=False, schema='partner')
    op.drop_column('usage_events', 'meta', schema='partner')
    op.add_column('usage_daily', sa.Column('avg_latency_ms', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('turn_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('p95_latency_ms', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('tokens_prompt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('tokens_completion', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    # ### end Alembic commands ###
