"""knowledgebase

Revision ID: 2076815b10a3
Revises: 9817b5a1033a
Create Date: 2025-11-13 11:27:24.019415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2076815b10a3'
down_revision: Union[str, Sequence[str], None] = '9817b5a1033a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('page_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_no IS NULL OR page_no >= 1', name=op.f('ck_document_pages_chk_document_pages_page_no_ge_1')),
    sa.ForeignKeyConstraint(['document_id'], ['user.documents.document_id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_document_pages_doc_page'),
    schema='user'
    )
    op.create_index('idx_document_pages_doc_page', 'document_pages', ['document_id', 'page_no'], unique=False, schema='user')
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('vector_memory', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 1', name=op.f('ck_document_chunks_chk_document_chunks_index_ge_1')),
    sa.ForeignKeyConstraint(['document_id'], ['user.documents.document_id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['user.document_pages.page_id'], name=op.f('fk_document_chunks_page_id_document_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_doc_idx'),
    schema='user'
    )
    op.create_index('idx_document_chunks_doc_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False, schema='user')
    op.create_index('idx_document_chunks_doc_page', 'document_chunks', ['document_id', 'page_id'], unique=False, schema='user')
    op.create_index('idx_document_chunks_vec_ivfflat', 'document_chunks', ['vector_memory'], unique=False, schema='user', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'vector_memory': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_chunks_vec_ivfflat', table_name='document_chunks', schema='user', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'vector_memory': 'vector_cosine_ops'})
    op.drop_index('idx_document_chunks_doc_page', table_name='document_chunks', schema='user')
    op.drop_index('idx_document_chunks_doc_index', table_name='document_chunks', schema='user')
    op.drop_table('document_chunks', schema='user')
    op.drop_index('idx_document_pages_doc_page', table_name='document_pages', schema='user')
    op.drop_table('document_pages', schema='user')
    # ### end Alembic commands ###
