"""cerate partner_promotion

Revision ID: 208006813af7
Revises: ab32d2c4ca18
Create Date: 2025-11-19 15:21:12.434118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208006813af7'
down_revision: Union[str, Sequence[str], None] = 'ab32d2c4ca18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_promotion_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=64), server_default=sa.text("'partner_admin'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_reason', sa.Text(), nullable=True),
    sa.Column('partner_id', sa.BigInteger(), nullable=True),
    sa.Column('partner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')", name=op.f('ck_partner_promotion_requests_chk_partner_promotion_status')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partners.id'], name=op.f('fk_partner_promotion_requests_partner_id_partners'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['partner.partner_users.id'], name=op.f('fk_partner_promotion_requests_partner_user_id_partner_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.users.user_id'], name=op.f('fk_partner_promotion_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_partner_promotion_requests')),
    schema='supervisor'
    )
    op.create_index('ix_partner_promo_status_req', 'partner_promotion_requests', ['status', 'requested_at'], unique=False, schema='supervisor')
    op.create_index('ix_partner_promo_user', 'partner_promotion_requests', ['user_id', 'requested_at'], unique=False, schema='supervisor')
    op.create_index('ux_partner_promo_pending_user', 'partner_promotion_requests', ['user_id'], unique=True, schema='supervisor', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_partner_promo_pending_user', table_name='partner_promotion_requests', schema='supervisor', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_partner_promo_user', table_name='partner_promotion_requests', schema='supervisor')
    op.drop_index('ix_partner_promo_status_req', table_name='partner_promotion_requests', schema='supervisor')
    op.drop_table('partner_promotion_requests', schema='supervisor')
    # ### end Alembic commands ###
