"""empty message

Revision ID: 22f0f6b321d8
Revises: 5eb24ecbb1e6
Create Date: 2025-12-02 15:59:05.051120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22f0f6b321d8'
down_revision: Union[str, Sequence[str], None] = '5eb24ecbb1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "classes",
        "allowed_model_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),  # ← 여기!
        existing_nullable=False,
        schema="partner",
    )
    op.add_column('org_llm_settings', sa.Column('org_id', sa.BigInteger(), nullable=False), schema='partner')
    op.drop_index(op.f('idx_org_llm_settings_partner'), table_name='org_llm_settings', schema='partner')
    op.drop_constraint(op.f('uq_org_llm_settings_partner'), 'org_llm_settings', schema='partner', type_='unique')
    op.create_index('idx_org_llm_settings_org', 'org_llm_settings', ['org_id'], unique=False, schema='partner')
    op.create_unique_constraint('uq_org_llm_settings_org', 'org_llm_settings', ['org_id'], schema='partner')
    op.drop_constraint(op.f('fk_org_llm_settings_partner_id_partners'), 'org_llm_settings', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_org_llm_settings_org_id_org'), 'org_llm_settings', 'org', ['org_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_column('org_llm_settings', 'partner_id', schema='partner')
    op.add_column('provider_credentials', sa.Column('org_id', sa.BigInteger(), nullable=False), schema='partner')
    op.drop_index(op.f('idx_provider_credentials_partner_provider'), table_name='provider_credentials', schema='partner')
    op.drop_constraint(op.f('uq_provider_credentials_partner_provider'), 'provider_credentials', schema='partner', type_='unique')
    op.create_index('idx_provider_credentials_org_provider', 'provider_credentials', ['org_id', 'provider'], unique=False, schema='partner')
    op.create_unique_constraint('uq_provider_credentials_org_provider', 'provider_credentials', ['org_id', 'provider'], schema='partner')
    op.drop_constraint(op.f('fk_provider_credentials_partner_id_partners'), 'provider_credentials', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provider_credentials_org_id_org'), 'provider_credentials', 'org', ['org_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_column('provider_credentials', 'partner_id', schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "classes",
        "allowed_model_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,  # 또는 기존 default가 있었으면 거기에 맞춰서
        existing_nullable=False,
        schema="partner",
    )

    op.drop_constraint(op.f('fk_provider_credentials_org_id_org'), 'provider_credentials', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provider_credentials_partner_id_partners'), 'provider_credentials', 'org', ['partner_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_constraint('uq_provider_credentials_org_provider', 'provider_credentials', schema='partner', type_='unique')
    op.drop_index('idx_provider_credentials_org_provider', table_name='provider_credentials', schema='partner')
    op.create_unique_constraint(op.f('uq_provider_credentials_partner_provider'), 'provider_credentials', ['partner_id', 'provider'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_provider_credentials_partner_provider'), 'provider_credentials', ['partner_id', 'provider'], unique=False, schema='partner')
    op.drop_column('provider_credentials', 'org_id', schema='partner')
    op.add_column('org_llm_settings', sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='partner')
    op.drop_constraint(op.f('fk_org_llm_settings_org_id_org'), 'org_llm_settings', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_org_llm_settings_partner_id_partners'), 'org_llm_settings', 'org', ['partner_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_constraint('uq_org_llm_settings_org', 'org_llm_settings', schema='partner', type_='unique')
    op.drop_index('idx_org_llm_settings_org', table_name='org_llm_settings', schema='partner')
    op.create_unique_constraint(op.f('uq_org_llm_settings_partner'), 'org_llm_settings', ['partner_id'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_llm_settings_partner'), 'org_llm_settings', ['partner_id'], unique=False, schema='partner')
    op.drop_column('org_llm_settings', 'org_id', schema='partner')
    op.alter_column('classes', 'allowed_model_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='partner')
    # ### end Alembic commands ###
