"""add partner.created_by

Revision ID: 346d6ea365ba
Revises: 94a2f6a6374c
Create Date: 2025-11-11 13:56:35.491404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346d6ea365ba'
down_revision: Union[str, Sequence[str], None] = '94a2f6a6374c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('created_by', sa.BigInteger(), nullable=True), schema='partner')
    op.create_index('idx_partners_created_by', 'partners', ['created_by'], unique=False, schema='partner')
    op.create_foreign_key(op.f('fk_partners_created_by_supervisors'), 'partners', 'supervisors', ['created_by'], ['user_id'], source_schema='partner', referent_schema='supervisor', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_partners_created_by_supervisors'), 'partners', schema='partner', type_='foreignkey')
    op.drop_index('idx_partners_created_by', table_name='partners', schema='partner')
    op.drop_column('partners', 'created_by', schema='partner')
    # ### end Alembic commands ###
