"""junction table

Revision ID: 38629e464cb1
Revises: 0262e7b2f425
Create Date: 2026-02-06 12:03:27.284042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38629e464cb1'
down_revision: Union[str, Sequence[str], None] = '0262e7b2f425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_documents',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['user.documents.knowledge_id'], name=op.f('fk_session_documents_knowledge_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user.practice_sessions.session_id'], name=op.f('fk_session_documents_session_id_practice_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'knowledge_id', name=op.f('pk_session_documents')),
    schema='user'
    )
    op.create_index('idx_session_documents_knowledge', 'session_documents', ['knowledge_id'], unique=False, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_documents_knowledge', table_name='session_documents', schema='user')
    op.drop_table('session_documents', schema='user')
    # ### end Alembic commands ###
