"""add_few_shot_ids

Revision ID: 3fea101de1e9
Revises: c6dc6bdc3087
Create Date: 2026-01-27 14:58:19.869455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fea101de1e9'
down_revision: Union[str, Sequence[str], None] = 'c6dc6bdc3087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_setting_few_shots_example'), table_name='practice_session_setting_few_shots', schema='user')
    op.drop_index(op.f('idx_setting_few_shots_setting'), table_name='practice_session_setting_few_shots', schema='user')
    op.drop_table('practice_session_setting_few_shots', schema='user')
    op.alter_column('practice_comparison_runs', 'model_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False,
               schema='user')
    op.alter_column('practice_comparison_runs', 'knowledge_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True,
               schema='user')
    op.add_column('practice_session_settings', sa.Column('few_shot_example_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), schema='user')
    op.drop_index(op.f('idx_practice_session_settings_few_shot_example'), table_name='practice_session_settings', schema='user')
    op.create_index('idx_practice_session_settings_few_shot_ids', 'practice_session_settings', ['few_shot_example_ids'], unique=False, schema='user', postgresql_using='gin')
    op.drop_constraint(op.f('fk_practice_session_settings_few_shot_example_id'), 'practice_session_settings', schema='user', type_='foreignkey')
    op.drop_column('practice_session_settings', 'few_shot_example_id', schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session_settings', sa.Column('few_shot_example_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='user')
    op.create_foreign_key(op.f('fk_practice_session_settings_few_shot_example_id'), 'practice_session_settings', 'few_shot_examples', ['few_shot_example_id'], ['example_id'], source_schema='user', referent_schema='user', ondelete='SET NULL')
    op.drop_index('idx_practice_session_settings_few_shot_ids', table_name='practice_session_settings', schema='user', postgresql_using='gin')
    op.create_index(op.f('idx_practice_session_settings_few_shot_example'), 'practice_session_settings', ['few_shot_example_id'], unique=False, schema='user')
    op.drop_column('practice_session_settings', 'few_shot_example_ids', schema='user')
    op.alter_column('practice_comparison_runs', 'knowledge_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True,
               schema='user')
    op.alter_column('practice_comparison_runs', 'model_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='user')
    op.create_table('practice_session_setting_few_shots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('setting_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('example_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['user.few_shot_examples.example_id'], name=op.f('fk_practice_session_setting_few_shots_example_id_few_sh_5ac0'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setting_id'], ['user.practice_session_settings.setting_id'], name=op.f('fk_practice_session_setting_few_shots_setting_id_practi_d885'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_session_setting_few_shots')),
    sa.UniqueConstraint('setting_id', 'example_id', name=op.f('uq_setting_example'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='user'
    )
    op.create_index(op.f('idx_setting_few_shots_setting'), 'practice_session_setting_few_shots', ['setting_id'], unique=False, schema='user')
    op.create_index(op.f('idx_setting_few_shots_example'), 'practice_session_setting_few_shots', ['example_id'], unique=False, schema='user')
    # ### end Alembic commands ###
