"""course

Revision ID: 412b8619c232
Revises: ff4aa6e54316
Create Date: 2025-11-10 13:41:06.947894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412b8619c232'
down_revision: Union[str, Sequence[str], None] = 'ff4aa6e54316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_codes', sa.Column('partner_id', sa.BigInteger(), nullable=False), schema='partner')
    op.add_column('invite_codes', sa.Column('target_role', sa.Text(), server_default=sa.text("'student'"), nullable=False), schema='partner')
    op.add_column('invite_codes', sa.Column('used_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('invite_codes', sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False), schema='partner')
    op.alter_column('invite_codes', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='partner')
    op.drop_index(op.f('idx_invite_codes_class_active'), table_name='invite_codes', schema='partner')
    op.create_index('idx_invite_codes_partner_status', 'invite_codes', ['partner_id', 'status'], unique=False, schema='partner')
    op.drop_constraint(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invite_codes_partner_id_partners'), 'invite_codes', 'partners', ['partner_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', 'classes', ['class_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='SET NULL')
    op.drop_column('invite_codes', 'is_active', schema='partner')
    op.drop_column('invite_codes', 'uses_count', schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_codes', sa.Column('uses_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('invite_codes', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='partner')
    op.drop_constraint(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', schema='partner', type_='foreignkey')
    op.drop_constraint(op.f('fk_invite_codes_partner_id_partners'), 'invite_codes', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', 'classes', ['class_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_index('idx_invite_codes_partner_status', table_name='invite_codes', schema='partner')
    op.create_index(op.f('idx_invite_codes_class_active'), 'invite_codes', ['class_id', 'is_active'], unique=False, schema='partner')
    op.alter_column('invite_codes', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='partner')
    op.drop_column('invite_codes', 'status', schema='partner')
    op.drop_column('invite_codes', 'used_count', schema='partner')
    op.drop_column('invite_codes', 'target_role', schema='partner')
    op.drop_column('invite_codes', 'partner_id', schema='partner')
    # ### end Alembic commands ###
