"""change_knowledge_ids_FK

Revision ID: 564ef1c1a784
Revises: f453ef3e5a7b
Create Date: 2025-12-19 12:05:06.496341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '564ef1c1a784'
down_revision: Union[str, Sequence[str], None] = 'f453ef3e5a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('knowledge_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), schema='user')
    op.drop_index(op.f('idx_practice_sessions_knowledge'), table_name='practice_sessions', schema='user')
    op.create_index('idx_practice_sessions_knowledge_ids', 'practice_sessions', ['knowledge_ids'], unique=False, schema='user', postgresql_using='gin')
    op.drop_constraint(op.f('fk_practice_sessions_knowledge'), 'practice_sessions', schema='user', type_='foreignkey')
    op.drop_column('practice_sessions', 'knowledge_id', schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('knowledge_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='user')
    op.create_foreign_key(op.f('fk_practice_sessions_knowledge'), 'practice_sessions', 'documents', ['knowledge_id'], ['knowledge_id'], source_schema='user', referent_schema='user', ondelete='SET NULL')
    op.drop_index('idx_practice_sessions_knowledge_ids', table_name='practice_sessions', schema='user', postgresql_using='gin')
    op.create_index(op.f('idx_practice_sessions_knowledge'), 'practice_sessions', ['knowledge_id'], unique=False, schema='user')
    op.drop_column('practice_sessions', 'knowledge_ids', schema='user')
    # ### end Alembic commands ###
