"""2025-12-03

Revision ID: 609db1bbf862
Revises: <새 리비전 ID>
Create Date: 2025-12-03 11:42:17.141017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609db1bbf862'
down_revision: Union[str, Sequence[str], None] = '<새 리비전 ID>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_credentials', sa.Column('partner_id', sa.BigInteger(), nullable=False), schema='partner')
    op.drop_index(op.f('idx_provider_credentials_org_provider'), table_name='provider_credentials', schema='partner')
    op.drop_constraint(op.f('uq_provider_credentials_org_provider'), 'provider_credentials', schema='partner', type_='unique')
    op.create_index('idx_provider_credentials_partner_provider', 'provider_credentials', ['partner_id', 'provider'], unique=False, schema='partner')
    op.create_unique_constraint('uq_provider_credentials_partner_provider', 'provider_credentials', ['partner_id', 'provider'], schema='partner')
    op.drop_constraint(op.f('fk_provider_credentials_org_id_org'), 'provider_credentials', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provider_credentials_partner_id_partners'), 'provider_credentials', 'partners', ['partner_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_column('provider_credentials', 'org_id', schema='partner')
    # 1) 기존 ongoing → active로 데이터 정리
    op.execute(
        "UPDATE partner.classes SET status = 'active' WHERE status = 'ongoing';"
    )

    # 2) 기존 체크 제약 삭제
    op.execute(
        "ALTER TABLE partner.classes DROP CONSTRAINT IF EXISTS chk_classes_status;"
    )

    # 3) 새로운 체크 제약 추가
    op.execute(
        "ALTER TABLE partner.classes "
        "ADD CONSTRAINT chk_classes_status "
        "CHECK (status IN ('planned','active','ended'));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_credentials', sa.Column('org_id', sa.BIGINT(), autoincrement=False, nullable=False), schema='partner')
    op.drop_constraint(op.f('fk_provider_credentials_partner_id_partners'), 'provider_credentials', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provider_credentials_org_id_org'), 'provider_credentials', 'org', ['org_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.drop_constraint('uq_provider_credentials_partner_provider', 'provider_credentials', schema='partner', type_='unique')
    op.drop_index('idx_provider_credentials_partner_provider', table_name='provider_credentials', schema='partner')
    op.create_unique_constraint(op.f('uq_provider_credentials_org_provider'), 'provider_credentials', ['org_id', 'provider'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_provider_credentials_org_provider'), 'provider_credentials', ['org_id', 'provider'], unique=False, schema='partner')
    op.drop_column('provider_credentials', 'partner_id', schema='partner')
    op.execute(
        "UPDATE partner.classes SET status = 'ongoing' WHERE status = 'active';"
    )

    op.execute(
        "ALTER TABLE partner.classes DROP CONSTRAINT IF EXISTS chk_classes_status;"
    )

    op.execute(
        "ALTER TABLE partner.classes "
        "ADD CONSTRAINT chk_classes_status "
        "CHECK (status IN ('planned','ongoing','ended'));"
    )
    # ### end Alembic commands ###
