"""empty message

Revision ID: 68e9c6e196ed
Revises: 9dcb16d63d1b
Create Date: 2025-11-27 12:03:04.747422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e9c6e196ed'
down_revision: Union[str, Sequence[str], None] = '9dcb16d63d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_classes_course_section'), 'classes', schema='partner', type_='unique')
    op.drop_column('classes', 'section_code', schema='partner')
    op.alter_column('courses', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='partner')
    op.drop_index(op.f('idx_partners_created'), table_name='org', schema='partner')
    op.drop_index(op.f('idx_partners_created_by'), table_name='org', schema='partner')
    op.drop_index(op.f('idx_partners_status'), table_name='org', schema='partner')
    op.drop_constraint(op.f('uq_partners_code'), 'org', schema='partner', type_='unique')
    op.create_index('idx_org_created', 'org', ['created_at'], unique=False, schema='partner')
    op.create_index('idx_org_created_by', 'org', ['created_by'], unique=False, schema='partner')
    op.create_index('idx_org_status', 'org', ['status'], unique=False, schema='partner')
    op.create_unique_constraint('uq_org_code', 'org', ['code'], schema='partner')
    op.drop_index(op.f('idx_partner_users_active'), table_name='partners', schema='partner')
    op.drop_index(op.f('idx_partner_users_last_login'), table_name='partners', schema='partner')
    op.drop_index(op.f('idx_partner_users_partner_email'), table_name='partners', schema='partner')
    op.drop_index(op.f('idx_partner_users_role'), table_name='partners', schema='partner')
    op.drop_constraint(op.f('uq_partner_users_partner_email'), 'partners', schema='partner', type_='unique')
    op.drop_constraint(op.f('uq_partner_users_partner_user'), 'partners', schema='partner', type_='unique')
    op.create_index('idx_partners_active', 'partners', ['is_active'], unique=False, schema='partner')
    op.create_index('idx_partners_email', 'partners', ['org_id', 'email'], unique=False, schema='partner')
    op.create_index('idx_partners_last_login', 'partners', ['last_login_at'], unique=False, schema='partner')
    op.create_index('idx_partners_role', 'partners', ['role'], unique=False, schema='partner')
    op.create_unique_constraint('uq_partners_org_email', 'partners', ['org_id', 'email'], schema='partner')
    op.create_unique_constraint('uq_partners_user_id', 'partners', ['user_id'], schema='partner')
    op.drop_constraint(op.f('fk_partner_promotion_requests_partner_id_partners'), 'partner_promotion_requests', schema='supervisor', type_='foreignkey')
    op.drop_constraint(op.f('fk_partner_promotion_requests_partner_user_id_partner_users'), 'partner_promotion_requests', schema='supervisor', type_='foreignkey')
    op.drop_column('partner_promotion_requests', 'partner_user_id', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'partner_id', schema='supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_promotion_requests', sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('partner_user_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='supervisor')
    op.create_foreign_key(op.f('fk_partner_promotion_requests_partner_user_id_partner_users'), 'partner_promotion_requests', 'partners', ['partner_user_id'], ['id'], source_schema='supervisor', referent_schema='partner', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_partner_promotion_requests_partner_id_partners'), 'partner_promotion_requests', 'org', ['partner_id'], ['id'], source_schema='supervisor', referent_schema='partner', ondelete='SET NULL')
    op.drop_constraint('uq_partners_user_id', 'partners', schema='partner', type_='unique')
    op.drop_constraint('uq_partners_org_email', 'partners', schema='partner', type_='unique')
    op.drop_index('idx_partners_role', table_name='partners', schema='partner')
    op.drop_index('idx_partners_last_login', table_name='partners', schema='partner')
    op.drop_index('idx_partners_email', table_name='partners', schema='partner')
    op.drop_index('idx_partners_active', table_name='partners', schema='partner')
    op.create_unique_constraint(op.f('uq_partner_users_partner_user'), 'partners', ['org_id', 'user_id'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_partner_users_partner_email'), 'partners', ['org_id', 'email'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_partner_users_role'), 'partners', ['role'], unique=False, schema='partner')
    op.create_index(op.f('idx_partner_users_partner_email'), 'partners', ['org_id', 'email'], unique=False, schema='partner')
    op.create_index(op.f('idx_partner_users_last_login'), 'partners', ['last_login_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_partner_users_active'), 'partners', ['is_active'], unique=False, schema='partner')
    op.drop_constraint('uq_org_code', 'org', schema='partner', type_='unique')
    op.drop_index('idx_org_status', table_name='org', schema='partner')
    op.drop_index('idx_org_created_by', table_name='org', schema='partner')
    op.drop_index('idx_org_created', table_name='org', schema='partner')
    op.create_unique_constraint(op.f('uq_partners_code'), 'org', ['code'], schema='partner', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_partners_status'), 'org', ['status'], unique=False, schema='partner')
    op.create_index(op.f('idx_partners_created_by'), 'org', ['created_by'], unique=False, schema='partner')
    op.create_index(op.f('idx_partners_created'), 'org', ['created_at'], unique=False, schema='partner')
    op.alter_column('courses', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='partner')
    op.add_column('classes', sa.Column('section_code', sa.TEXT(), autoincrement=False, nullable=True), schema='partner')
    op.create_unique_constraint(op.f('uq_classes_course_section'), 'classes', ['course_id', 'section_code'], schema='partner', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
