"""01-07_usage

Revision ID: 72dd40c64d15
Revises: a2f44d887975
Create Date: 2026-01-07 17:12:19.781973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72dd40c64d15'
down_revision: Union[str, Sequence[str], None] = 'a2f44d887975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_model_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('request_type', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("date_trunc('month', month::timestamp) = month::timestamp", name=op.f('ck_usage_model_monthly_chk_usage_model_month_first_day')),
    sa.CheckConstraint('request_count >= 0 AND total_tokens >= 0 AND total_cost_usd >= 0', name=op.f('ck_usage_model_monthly_chk_usage_model_monthly_nonneg')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.org.id'], name=op.f('fk_usage_model_monthly_partner_id_org'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_model_monthly')),
    sa.UniqueConstraint('partner_id', 'month', 'request_type', 'provider', 'model_name', name='uq_usage_model_monthly_key'),
    schema='partner'
    )
    op.create_index('idx_usage_model_monthly_partner_month', 'usage_model_monthly', ['partner_id', 'month'], unique=False, schema='partner')
    op.create_index('idx_usage_model_monthly_provider_model', 'usage_model_monthly', ['provider', 'model_name'], unique=False, schema='partner')
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('turn_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('partner_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('enrollment_id', sa.BigInteger(), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('response_id', sa.BigInteger(), nullable=True),
    sa.Column('request_type', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('media_duration_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.CheckConstraint('tokens_prompt >= 0 AND tokens_completion >= 0 AND total_tokens >= 0 AND media_duration_seconds >= 0 AND total_cost_usd >= 0', name=op.f('ck_usage_events_chk_usage_events_nonneg')),
    sa.ForeignKeyConstraint(['class_id'], ['partner.classes.id'], name=op.f('fk_usage_events_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['partner.enrollments.id'], name=op.f('fk_usage_events_enrollment_id_enrollments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.org.id'], name=op.f('fk_usage_events_partner_id_org'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['partner.ai_sessions.id'], name=op.f('fk_usage_events_session_id_ai_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['partner.students.id'], name=op.f('fk_usage_events_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events')),
    sa.UniqueConstraint('request_id', name='uq_usage_events_request_id'),
    schema='partner'
    )
    op.create_index('idx_usage_events_class_time', 'usage_events', ['class_id', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_partner_provider_model_time', 'usage_events', ['partner_id', 'provider', 'model_name', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_partner_time', 'usage_events', ['partner_id', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_partner_type_time', 'usage_events', ['partner_id', 'request_type', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_student_time', 'usage_events', ['student_id', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_success_time', 'usage_events', ['success', 'occurred_at'], unique=False, schema='partner')
    op.create_index('idx_usage_events_turn_id', 'usage_events', ['turn_id'], unique=False, schema='partner')
    op.drop_index(op.f('idx_usage_events_stt_class_time'), table_name='usage_events_stt', schema='partner')
    op.drop_index(op.f('idx_usage_events_stt_provider_time'), table_name='usage_events_stt', schema='partner')
    op.drop_index(op.f('idx_usage_events_stt_session_time'), table_name='usage_events_stt', schema='partner')
    op.drop_index(op.f('idx_usage_events_stt_student_time'), table_name='usage_events_stt', schema='partner')
    op.drop_table('usage_events_stt', schema='partner')
    op.drop_index(op.f('idx_usage_events_llm_class_time'), table_name='usage_events_llm', schema='partner')
    op.drop_index(op.f('idx_usage_events_llm_provider_model_time'), table_name='usage_events_llm', schema='partner')
    op.drop_index(op.f('idx_usage_events_llm_session_time'), table_name='usage_events_llm', schema='partner')
    op.drop_index(op.f('idx_usage_events_llm_student_time'), table_name='usage_events_llm', schema='partner')
    op.drop_index(op.f('idx_usage_events_llm_success_time'), table_name='usage_events_llm', schema='partner')
    op.drop_table('usage_events_llm', schema='partner')
    op.drop_index(op.f('idx_api_cost_daily_partner_date'), table_name='api_cost_daily', schema='partner')
    op.drop_index(op.f('idx_api_cost_daily_provider_date'), table_name='api_cost_daily', schema='partner')
    op.drop_table('api_cost_daily', schema='partner')
    op.drop_index(op.f('idx_model_usage_monthly_partner_month'), table_name='model_usage_monthly', schema='partner')
    op.drop_index(op.f('idx_model_usage_monthly_provider_model'), table_name='model_usage_monthly', schema='partner')
    op.drop_table('model_usage_monthly', schema='partner')
    op.add_column('usage_daily', sa.Column('dim_type', sa.Text(), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('dim_id', sa.BigInteger(), nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('request_type', sa.Text(), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('model_name', sa.Text(), nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('request_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('turn_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('session_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('tokens_prompt', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('tokens_completion', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('media_duration_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('success_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('avg_latency_ms', sa.Numeric(precision=14, scale=2), nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('p95_latency_ms', sa.Numeric(precision=14, scale=2), nullable=True), schema='partner')
    op.drop_index(op.f('idx_usage_daily_class_date'), table_name='usage_daily', schema='partner')
    op.drop_index(op.f('idx_usage_daily_enrollment_date'), table_name='usage_daily', schema='partner')
    op.drop_index(op.f('idx_usage_daily_student_date'), table_name='usage_daily', schema='partner')
    op.drop_index(op.f('uq_usage_daily_class'), table_name='usage_daily', schema='partner', postgresql_where='((enrollment_id IS NULL) AND (class_id IS NOT NULL))')
    op.drop_index(op.f('uq_usage_daily_enrollment'), table_name='usage_daily', schema='partner', postgresql_where='(enrollment_id IS NOT NULL)')
    op.drop_index(op.f('uq_usage_daily_student'), table_name='usage_daily', schema='partner', postgresql_where='((enrollment_id IS NULL) AND (class_id IS NULL) AND (student_id IS NOT NULL))')
    op.create_index('idx_usage_daily_partner_date', 'usage_daily', ['partner_id', 'usage_date'], unique=False, schema='partner')
    op.create_index('idx_usage_daily_partner_dim_date', 'usage_daily', ['partner_id', 'dim_type', 'usage_date'], unique=False, schema='partner')
    op.create_index('idx_usage_daily_type_provider_date', 'usage_daily', ['request_type', 'provider', 'usage_date'], unique=False, schema='partner')
    op.create_index('uq_usage_daily_key', 'usage_daily', ['partner_id', 'usage_date', 'dim_type', 'dim_id', 'request_type', 'provider', sa.literal_column("coalesce(model_name,'')")], unique=True, schema='partner')
    op.drop_constraint(op.f('fk_usage_daily_enrollment_id_enrollments'), 'usage_daily', schema='partner', type_='foreignkey')
    op.drop_constraint(op.f('fk_usage_daily_class_id_classes'), 'usage_daily', schema='partner', type_='foreignkey')
    op.drop_constraint(op.f('fk_usage_daily_student_id_students'), 'usage_daily', schema='partner', type_='foreignkey')
    op.drop_column('usage_daily', 'student_id', schema='partner')
    op.drop_column('usage_daily', 'class_id', schema='partner')
    op.drop_column('usage_daily', 'total_cost', schema='partner')
    op.drop_column('usage_daily', 'total_messages', schema='partner')
    op.drop_column('usage_daily', 'enrollment_id', schema='partner')
    op.drop_column('usage_daily', 'total_sessions', schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_daily', sa.Column('total_sessions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('enrollment_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('total_messages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('total_cost', sa.NUMERIC(precision=14, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='partner')
    op.add_column('usage_daily', sa.Column('class_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='partner')
    op.add_column('usage_daily', sa.Column('student_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='partner')
    op.create_foreign_key(op.f('fk_usage_daily_student_id_students'), 'usage_daily', 'students', ['student_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_usage_daily_class_id_classes'), 'usage_daily', 'classes', ['class_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_usage_daily_enrollment_id_enrollments'), 'usage_daily', 'enrollments', ['enrollment_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='SET NULL')
    op.drop_index('uq_usage_daily_key', table_name='usage_daily', schema='partner')
    op.drop_index('idx_usage_daily_type_provider_date', table_name='usage_daily', schema='partner')
    op.drop_index('idx_usage_daily_partner_dim_date', table_name='usage_daily', schema='partner')
    op.drop_index('idx_usage_daily_partner_date', table_name='usage_daily', schema='partner')
    op.create_index(op.f('uq_usage_daily_student'), 'usage_daily', ['partner_id', 'student_id', 'usage_date', 'provider'], unique=True, schema='partner', postgresql_where='((enrollment_id IS NULL) AND (class_id IS NULL) AND (student_id IS NOT NULL))')
    op.create_index(op.f('uq_usage_daily_enrollment'), 'usage_daily', ['enrollment_id', 'usage_date', 'provider'], unique=True, schema='partner', postgresql_where='(enrollment_id IS NOT NULL)')
    op.create_index(op.f('uq_usage_daily_class'), 'usage_daily', ['partner_id', 'class_id', 'usage_date', 'provider'], unique=True, schema='partner', postgresql_where='((enrollment_id IS NULL) AND (class_id IS NOT NULL))')
    op.create_index(op.f('idx_usage_daily_student_date'), 'usage_daily', ['student_id', 'usage_date'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_daily_enrollment_date'), 'usage_daily', ['enrollment_id', 'usage_date'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_daily_class_date'), 'usage_daily', ['class_id', 'usage_date'], unique=False, schema='partner')
    op.drop_column('usage_daily', 'p95_latency_ms', schema='partner')
    op.drop_column('usage_daily', 'avg_latency_ms', schema='partner')
    op.drop_column('usage_daily', 'total_cost_usd', schema='partner')
    op.drop_column('usage_daily', 'error_count', schema='partner')
    op.drop_column('usage_daily', 'success_count', schema='partner')
    op.drop_column('usage_daily', 'media_duration_seconds', schema='partner')
    op.drop_column('usage_daily', 'tokens_completion', schema='partner')
    op.drop_column('usage_daily', 'tokens_prompt', schema='partner')
    op.drop_column('usage_daily', 'message_count', schema='partner')
    op.drop_column('usage_daily', 'session_count', schema='partner')
    op.drop_column('usage_daily', 'turn_count', schema='partner')
    op.drop_column('usage_daily', 'request_count', schema='partner')
    op.drop_column('usage_daily', 'model_name', schema='partner')
    op.drop_column('usage_daily', 'request_type', schema='partner')
    op.drop_column('usage_daily', 'dim_id', schema='partner')
    op.drop_column('usage_daily', 'dim_type', schema='partner')
    op.create_table('model_usage_monthly',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint("date_trunc('month'::text, month::timestamp without time zone) = month::timestamp without time zone", name=op.f('ck_model_usage_monthly_chk_model_usage_month_first_day')),
    sa.CheckConstraint('session_count >= 0 AND total_tokens >= 0 AND total_cost >= 0::numeric', name=op.f('ck_model_usage_monthly_chk_model_usage_monthly_nonneg')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.org.id'], name=op.f('fk_model_usage_monthly_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_usage_monthly')),
    sa.UniqueConstraint('partner_id', 'month', 'provider', 'model_name', name=op.f('uq_model_usage_monthly_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='partner'
    )
    op.create_index(op.f('idx_model_usage_monthly_provider_model'), 'model_usage_monthly', ['provider', 'model_name'], unique=False, schema='partner')
    op.create_index(op.f('idx_model_usage_monthly_partner_month'), 'model_usage_monthly', ['partner_id', 'month'], unique=False, schema='partner')
    op.create_table('api_cost_daily',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('usage_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.CheckConstraint('total_cost >= 0::numeric', name=op.f('ck_api_cost_daily_chk_api_cost_daily_cost_nonneg')),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.org.id'], name=op.f('fk_api_cost_daily_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_cost_daily')),
    sa.UniqueConstraint('partner_id', 'usage_date', 'provider', name=op.f('uq_api_cost_daily_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='partner'
    )
    op.create_index(op.f('idx_api_cost_daily_provider_date'), 'api_cost_daily', ['provider', 'usage_date'], unique=False, schema='partner')
    op.create_index(op.f('idx_api_cost_daily_partner_date'), 'api_cost_daily', ['partner_id', 'usage_date'], unique=False, schema='partner')
    op.create_table('usage_events_llm',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tokens_prompt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tokens_completion', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('tokens_prompt >= 0 AND tokens_completion >= 0 AND total_cost >= 0::numeric', name=op.f('ck_usage_events_llm_chk_usage_events_llm_nonneg')),
    sa.ForeignKeyConstraint(['class_id'], ['partner.classes.id'], name=op.f('fk_usage_events_llm_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['partner.ai_sessions.id'], name=op.f('fk_usage_events_llm_session_id_ai_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['partner.students.id'], name=op.f('fk_usage_events_llm_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events_llm')),
    schema='partner'
    )
    op.create_index(op.f('idx_usage_events_llm_success_time'), 'usage_events_llm', ['success', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_llm_student_time'), 'usage_events_llm', ['student_id', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_llm_session_time'), 'usage_events_llm', ['session_id', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_llm_provider_model_time'), 'usage_events_llm', ['provider', 'model_name', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_llm_class_time'), 'usage_events_llm', ['class_id', 'recorded_at'], unique=False, schema='partner')
    op.create_table('usage_events_stt',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_duration_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=14, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('media_duration_seconds >= 0 AND total_cost >= 0::numeric', name=op.f('ck_usage_events_stt_chk_usage_events_stt_nonneg')),
    sa.ForeignKeyConstraint(['class_id'], ['partner.classes.id'], name=op.f('fk_usage_events_stt_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['partner.ai_sessions.id'], name=op.f('fk_usage_events_stt_session_id_ai_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['partner.students.id'], name=op.f('fk_usage_events_stt_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events_stt')),
    schema='partner'
    )
    op.create_index(op.f('idx_usage_events_stt_student_time'), 'usage_events_stt', ['student_id', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_stt_session_time'), 'usage_events_stt', ['session_id', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_stt_provider_time'), 'usage_events_stt', ['provider', 'recorded_at'], unique=False, schema='partner')
    op.create_index(op.f('idx_usage_events_stt_class_time'), 'usage_events_stt', ['class_id', 'recorded_at'], unique=False, schema='partner')
    op.drop_index('idx_usage_events_turn_id', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_success_time', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_student_time', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_partner_type_time', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_partner_time', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_partner_provider_model_time', table_name='usage_events', schema='partner')
    op.drop_index('idx_usage_events_class_time', table_name='usage_events', schema='partner')
    op.drop_table('usage_events', schema='partner')
    op.drop_index('idx_usage_model_monthly_provider_model', table_name='usage_model_monthly', schema='partner')
    op.drop_index('idx_usage_model_monthly_partner_month', table_name='usage_model_monthly', schema='partner')
    op.drop_table('usage_model_monthly', schema='partner')
    # ### end Alembic commands ###
