"""renovate_promote_table

Revision ID: 8436c9b3fe33
Revises: f774899a4fb3
Create Date: 2025-11-20 15:50:35.537777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8436c9b3fe33'
down_revision: Union[str, Sequence[str], None] = 'f774899a4fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_promotion_requests', sa.Column('name', sa.String(length=255), nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('email', sa.String(length=255), nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('org_name', sa.String(length=255), nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('edu_category', sa.String(length=64), nullable=True), schema='supervisor')
    op.drop_column('partner_promotion_requests', 'decided_reason', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'phone_number', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'requested_org_name', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'meta', schema='supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_promotion_requests', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('requested_org_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('phone_number', sa.VARCHAR(length=32), autoincrement=False, nullable=False), schema='supervisor')
    op.add_column('partner_promotion_requests', sa.Column('decided_reason', sa.TEXT(), autoincrement=False, nullable=True), schema='supervisor')
    op.drop_column('partner_promotion_requests', 'edu_category', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'org_name', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'email', schema='supervisor')
    op.drop_column('partner_promotion_requests', 'name', schema='supervisor')
    # ### end Alembic commands ###
