"""add_practice_comparison_runs

Revision ID: 95e2356b06a6
Revises: 1c23a7df19c7
Create Date: 2026-01-22 13:47:09.675106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e2356b06a6'
down_revision: Union[str, Sequence[str], None] = '1c23a7df19c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_comparison_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('panel_a_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('panel_b_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(prompt_text) > 0', name=op.f('ck_practice_comparison_runs_chk_practice_comparison_runs_prompt_nonempty')),
    sa.ForeignKeyConstraint(['session_id'], ['user.practice_sessions.session_id'], name=op.f('fk_practice_comparison_runs_session_id_practice_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_comparison_runs')),
    schema='user'
    )
    op.create_index('idx_practice_comparison_runs_session_time', 'practice_comparison_runs', ['session_id', 'created_at'], unique=False, schema='user')
    op.add_column('practice_responses', sa.Column('comparison_run_id', sa.BigInteger(), nullable=True), schema='user')
    op.add_column('practice_responses', sa.Column('panel_key', sa.Text(), nullable=True), schema='user')
    op.create_index('idx_practice_responses_comparison_run', 'practice_responses', ['comparison_run_id'], unique=False, schema='user')
    op.create_foreign_key(op.f('fk_practice_responses_comparison_run_id_practice_comparison_runs'), 'practice_responses', 'practice_comparison_runs', ['comparison_run_id'], ['id'], source_schema='user', referent_schema='user', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_practice_responses_comparison_run_id_practice_comparison_runs'), 'practice_responses', schema='user', type_='foreignkey')
    op.drop_index('idx_practice_responses_comparison_run', table_name='practice_responses', schema='user')
    op.drop_column('practice_responses', 'panel_key', schema='user')
    op.drop_column('practice_responses', 'comparison_run_id', schema='user')
    op.drop_index('idx_practice_comparison_runs_session_time', table_name='practice_comparison_runs', schema='user')
    op.drop_table('practice_comparison_runs', schema='user')
    # ### end Alembic commands ###
