"""fixed_create_class_and_inviting

Revision ID: 9cce79e5687c
Revises: ea0f1a62093d
Create Date: 2025-11-24 15:19:53.939581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cce79e5687c'
down_revision: Union[str, Sequence[str], None] = 'ea0f1a62093d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_codes', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='partner')
    op.create_index('idx_invite_codes_class_status', 'invite_codes', ['class_id', 'status'], unique=False, schema='partner')
    op.drop_constraint(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', 'classes', ['class_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='CASCADE')
    op.create_index('idx_users_is_partner_created', 'users', ['is_partner', 'created_at'], unique=False, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_is_partner_created', table_name='users', schema='user')
    op.drop_constraint(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', schema='partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invite_codes_class_id_classes'), 'invite_codes', 'classes', ['class_id'], ['id'], source_schema='partner', referent_schema='partner', ondelete='SET NULL')
    op.drop_index('idx_invite_codes_class_status', table_name='invite_codes', schema='partner')
    op.alter_column('invite_codes', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='partner')
    # ### end Alembic commands ###
