"""prompt_ids

Revision ID: b328f6ef1f1f
Revises: 3fea101de1e9
Create Date: 2026-01-28 14:33:04.570158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b328f6ef1f1f'
down_revision: Union[str, Sequence[str], None] = '3fea101de1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('prompt_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), schema='user')
    op.drop_index(op.f('idx_practice_sessions_agent'), table_name='practice_sessions', schema='user')
    op.create_index('idx_practice_sessions_prompt_ids', 'practice_sessions', ['prompt_ids'], unique=False, schema='user', postgresql_using='gin')
    op.drop_constraint(op.f('fk_practice_sessions_agent_id_ai_agents'), 'practice_sessions', schema='user', type_='foreignkey')
    op.drop_column('practice_sessions', 'agent_id', schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_sessions', sa.Column('agent_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='user')
    op.create_foreign_key(op.f('fk_practice_sessions_agent_id_ai_agents'), 'practice_sessions', 'ai_agents', ['agent_id'], ['agent_id'], source_schema='user', referent_schema='user', ondelete='SET NULL')
    op.drop_index('idx_practice_sessions_prompt_ids', table_name='practice_sessions', schema='user', postgresql_using='gin')
    op.create_index(op.f('idx_practice_sessions_agent'), 'practice_sessions', ['agent_id'], unique=False, schema='user')
    op.drop_column('practice_sessions', 'prompt_ids', schema='user')
    # ### end Alembic commands ###
