"""delete_user_partner_promotion

Revision ID: ccd4f818823f
Revises: 1eb9b5e9b252
Create Date: 2025-11-19 17:26:46.987841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd4f818823f'
down_revision: Union[str, Sequence[str], None] = '1eb9b5e9b252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_promotion_requests', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=True,
               schema='supervisor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_promotion_requests', 'email',
               existing_type=postgresql.CITEXT(),
               nullable=False,
               schema='supervisor')
    # ### end Alembic commands ###
