"""fewshot_refactoring

Revision ID: e0377ccc47aa
Revises: d8d232eb05ee
Create Date: 2026-02-02 14:15:54.638368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0377ccc47aa'
down_revision: Union[str, Sequence[str], None] = 'd8d232eb05ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_agent_shares_agent_class'), 'prompt_shares', schema='user', type_='unique')
    op.create_unique_constraint('uq_prompt_shares_prompt_class', 'prompt_shares', ['prompt_id', 'class_id'], schema='user')
    op.drop_constraint(op.f('uq_agent_usage_stats_agent_id'), 'prompt_usage_stats', schema='user', type_='unique')
    op.create_unique_constraint(op.f('uq_prompt_usage_stats_prompt_id'), 'prompt_usage_stats', ['prompt_id'], schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_prompt_usage_stats_prompt_id'), 'prompt_usage_stats', schema='user', type_='unique')
    op.create_unique_constraint(op.f('uq_agent_usage_stats_agent_id'), 'prompt_usage_stats', ['prompt_id'], schema='user', postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_prompt_shares_prompt_class', 'prompt_shares', schema='user', type_='unique')
    op.create_unique_constraint(op.f('uq_agent_shares_agent_class'), 'prompt_shares', ['prompt_id', 'class_id'], schema='user', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
