"""adding_agent_id_FK

Revision ID: f453ef3e5a7b
Revises: fb288a0c875e
Create Date: 2025-12-18 17:11:06.010872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f453ef3e5a7b'
down_revision: Union[str, Sequence[str], None] = 'fb288a0c875e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session_settings', sa.Column('agent_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), schema='user')
    op.add_column('practice_sessions', sa.Column('agent_id', sa.BigInteger(), nullable=True), schema='user')
    op.create_index('idx_practice_sessions_agent', 'practice_sessions', ['agent_id'], unique=False, schema='user')
    op.create_foreign_key(op.f('fk_practice_sessions_agent_id_ai_agents'), 'practice_sessions', 'ai_agents', ['agent_id'], ['agent_id'], source_schema='user', referent_schema='user', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_practice_sessions_agent_id_ai_agents'), 'practice_sessions', schema='user', type_='foreignkey')
    op.drop_index('idx_practice_sessions_agent', table_name='practice_sessions', schema='user')
    op.drop_column('practice_sessions', 'agent_id', schema='user')
    op.drop_column('practice_session_settings', 'agent_snapshot', schema='user')
    # ### end Alembic commands ###
