"""2025-12-18

Revision ID: fb288a0c875e
Revises: db3c21fe32bf
Create Date: 2025-12-18 10:18:36.468082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb288a0c875e'
down_revision: Union[str, Sequence[str], None] = 'db3c21fe32bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_agents', 'icon', schema='user')
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'uploading'"),
               existing_nullable=False,
               schema='user')
    op.alter_column('documents', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False,
               schema='user')
    op.drop_index(op.f('idx_practice_responses_model_time'), table_name='practice_responses', schema='user')
    op.drop_index(op.f('idx_practice_responses_session_time'), table_name='practice_responses', schema='user')
    op.drop_index(op.f('uq_practice_session_models_primary_once'), table_name='practice_session_models', schema='user', postgresql_where='(is_primary = true)')
    op.drop_constraint(op.f('uq_practice_session_models_session_model'), 'practice_session_models', schema='user', type_='unique')
    op.drop_index(op.f('idx_practice_sessions_project'), table_name='practice_sessions', schema='user')
    op.drop_index(op.f('idx_practice_sessions_user_time'), table_name='practice_sessions', schema='user')
    op.create_index('idx_practice_sessions_user', 'practice_sessions', ['user_id'], unique=False, schema='user')
    op.drop_column('practice_sessions', 'status', schema='user')
    op.drop_column('practice_sessions', 'completed_at', schema='user')
    op.drop_column('practice_sessions', 'started_at', schema='user')
    op.alter_column('projects', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='user')
    op.create_unique_constraint('uq_projects_owner_class_name', 'projects', ['owner_id', 'class_id', 'name'], schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_owner_class_name', 'projects', schema='user', type_='unique')
    op.alter_column('projects', 'class_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='user')
    op.add_column('practice_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='user')
    op.add_column('practice_sessions', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='user')
    op.add_column('practice_sessions', sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False), schema='user')
    op.drop_index('idx_practice_sessions_user', table_name='practice_sessions', schema='user')
    op.create_index(op.f('idx_practice_sessions_user_time'), 'practice_sessions', ['user_id', 'started_at'], unique=False, schema='user')
    op.create_index(op.f('idx_practice_sessions_project'), 'practice_sessions', ['project_id'], unique=False, schema='user')
    op.create_unique_constraint(op.f('uq_practice_session_models_session_model'), 'practice_session_models', ['session_id', 'model_name'], schema='user', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_practice_session_models_primary_once'), 'practice_session_models', ['session_id'], unique=True, schema='user', postgresql_where='(is_primary = true)')
    op.create_index(op.f('idx_practice_responses_session_time'), 'practice_responses', ['session_id', 'created_at'], unique=False, schema='user')
    op.create_index(op.f('idx_practice_responses_model_time'), 'practice_responses', ['session_model_id', 'created_at'], unique=False, schema='user')
    op.alter_column('documents', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='user')
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'processing'::text"),
               existing_nullable=False,
               schema='user')
    op.add_column('ai_agents', sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True), schema='user')
    # ### end Alembic commands ###
